# Build da biblioteca
cc_library(
    name = "teste",
    srcs = ["teste.cpp"],
    hdrs = ["teste.h"],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "generic",
    visibility = ["//visibility:public"]
)